@id=1e9db66f-ce99-4747-8860-d22075624b07

###
POST http://0.0.0.0:8086/dev/post HTTP/1.1
Content-Type: application/json

{
  "authur": "meeky",
  "content": "comment on this",
  "views": 4,
  "likes": 59,
  "comments": []
}

###
GET http://0.0.0.0:8086/dev/post/{{id}} HTTP/1.1
Content-Type: application/json

###
GET http://0.0.0.0:8086/dev/post  HTTP/1.1
Content-Type: application/json

###
PUT http://0.0.0.0:8086/dev/post/{{id}}
Content-Type: application/json

{
  "authur": "meeky.ae"
}

###
DELETE http://0.0.0.0:8086/dev/post/{{id}}
Content-Type: application/json
